name: Build
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: "ubuntu-latest"
    
    name: Test JDK 17 unbuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Maven Compile
        run: mvn -X compile -B --file pom.xml

      - name: Maven Verify
        run: mvn -X verify -B --file pom.xml
...
